# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b23f79b9b005af74b2f17ff1f23d53356ccd5dcf984d4f116fb58c6374b1927f4b1b82abcf9d45515c6c38be415e6d8adf3893f7393301edc30dacc381f5f9ce

test:
  secret_key_base: 85421e236ea4791884f378011d0bcf9237962facb313858b1e69de298f6bdea9eb1a6eefb12fbf2d63cf96300edd79c507c5ac2ac443fa2bba74e038a8c7ddf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
